### ISSUE TITLE
Step by Step Walkthrough out of date

### ISSUE THREAD

**Issue by JonathanCSmith** [guijacquemet/Fast4DReg#1]
The step by step walkthrough appears to reference deprecated code / modality of work. 

The line: "Open the "estimate-drift" script and click run. The user interface opens." in the readme should probably be correct to use the current script names & perhaps and indication of where/how to find them in the menu.

**Comment by jpylvanainen** [comment]
Thanks, @JonathanCSmith for noticing this. I will edit the documentation so that it is up to date.

**Comment by jpylvanainen** [comment]
@JonathanCSmith Updates are now done with the new release. Any new comments or corrections are very welcome. Cheers!
